### ISSUE TITLE
The auth method

### ISSUE THREAD

**Issue by Impavidity** [zserg/onenotecli#1]
I am new to onenote api and I can not figure out how it works in your code.
Can you give me more detail instructions on this? What's the function of HOST and PORT? Does it mean that I need to create a host to receive the token?

**Comment by zserg** [comment]
Before using onenote api you have to register your application in microsoft dev center (https://msdn.microsoft.com/en-us/office/office365/howto/onenote-auth#register-msa). There you have to specify "Redirect URIs" parameter, e.g (http://localhost:8085 ), where you will be redirected to when OAUth2 procedure is going. HOST and PORT should  be the same as in Redirect URI. 
There is option "redirect_url" in onenotecli, but as I see it's not working for now.
